joint_name_to_servo_id: {
  THUMB0: 33,
  THUMB1: 9,
  THUMB2: 19,
  INDEX0: 17,
  INDEX1: 15,
  INDEX2: 1,
  INDEX3: 11,
  MIDDLE0: 27,
  MIDDLE1: 25,
  MIDDLE2: 23,
  MIDDLE3: 13,
  RING0: 30,
  RING1: 28,
  RING2: 34,
  RING3: 26,
  LITTLE0: 6,
  LITTLE1: 4,
  LITTLE2: 2,
  LITTLE3: 20,  
}
